{{- if and .Values.selfSigned.enabled .Values.selfSigned.caCertBase64 }}
apiVersion: v1
kind: Secret
metadata:
  name: ca-cert-secret
  labels:
    app: {{ include "kubernetes-agent.fullname" . }}
type: Opaque
data:
  ca.crt: {{ .Values.selfSigned.caCertBase64 | b64enc | quote }}
{{- end }}
