apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kubernetes-agent.fullname" . }}
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubernetes-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubernetes-agent.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kubernetes-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- if .Values.selfSigned.enabled }}
      initContainers:
        - name: setup-ca-cert
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Decoding CA Certificate..."
              base64 -d /tmp/ca-secret/ca.crt > /etc/ssl/certs/custom-ca.pem
              echo "Updating CA Trust..."
              update-ca-certificates || true
          volumeMounts:
            - name: ca-cert-volume
              mountPath: /tmp/ca-secret
            - name: ca-cert-location
              mountPath: /etc/ssl/certs/
      {{- end }}

      containers:
        - name: "{{ template "kubernetes-agent.fullname" . }}-broker"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.broker.repository }}:{{ .Values.image.broker.tag }}"
          imagePullPolicy: {{ .Values.image.broker.pullPolicy }}
          resources:
            {{- toYaml .Values.resources.broker | nindent 12 }}
          env:
           - name: BROKER_IDENTIFIER
             valueFrom:
              secretKeyRef:
                name: {{ include "kubernetes-agent.fullname" . }}
                key: identifier
           - name: BROKER_ENDPOINT
             value: {{ .Values.agent.endpoint }}
          {{- if .Values.agent.proxy }}
           - name: BROKER_PROXY
             value: {{ .Values.agent.proxy }}
          {{- end }}
          {{- if .Values.selfSigned.enabled }}
          volumeMounts:
            - name: ca-cert-location
              mountPath: /etc/ssl/certs/custom-ca.pem
              subPath: custom-ca.pem
          {{- end }}

        - name: "{{ template "kubernetes-agent.fullname" . }}-proxy"
          image: "{{ .Values.image.proxy.repository }}:{{ .Values.image.proxy.tag }}"
          imagePullPolicy: {{ .Values.image.proxy.pullPolicy }}
          resources:
            {{- toYaml .Values.resources.proxy | nindent 12 }}
          ports:
          - containerPort: 8001
          livenessProbe:
            tcpSocket:
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if .Values.selfSigned.enabled }}
      volumes:
        - name: ca-cert-volume
          secret:
            secretName: ca-cert-secret
        - name: ca-cert-location
          emptyDir: {}
      {{- end }}
