apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-agent.fullname" . }}
type: Opaque
stringData:
  identifier: {{ required "agent.identifier is required!" .Values.agent.identifier }}
